version: "3.9"
services:
  bankdb:
    image: mysql:8
    container_name: bankdb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bankdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  kk-04-rest:
    build: .
    container_name: kk-04-rest
    depends_on:
      - bankdb:
            condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data: